sonar.projectKey=Code-Illuminators_Illuminators_frontend
sonar.organization=code-illuminators
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=src/tests/**
sonar.coverage.exclusions=src/tests/**